apiVersion: apps/v1
kind: Deployment
metadata:
  name: geography-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geography-db
  template:
    metadata:
      labels:
        app: geography-db
    spec:
      containers:
        - name: geography-db
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          resources:
            limits:
              memory: "{{ .Values.mongo.resources.limits.memory }}"
              cpu: "{{ .Values.mongo.resources.limits.cpu }}"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              value: "geographydb"
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
