apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: {{ .Values.mongo.persistentVolume.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.mongo.persistentVolume.hostPath }}"
