apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.secret.username }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.secret.password }}
