apiVersion: apps/v1
kind: Deployment
metadata:
  name: geography-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geography-server
  template:
    metadata:
      labels:
        app: geography-server
    spec:
      containers:
        - name: geography-server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          resources:
            limits:
              memory: "{{ .Values.server.resources.limits.memory }}"
              cpu: "{{ .Values.server.resources.limits.cpu }}"
          ports:
            - containerPort: {{ .Values.server.containerPort }}
          env:
            - name: MONGODB_URL
              value: "{{ .Values.server.env.MONGODB_URL }}"
