apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prog-kyiv-ua
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 10
    volumeSize: 80
    ssh:
      # allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      publicKeyPath: /Users/ymaksymchuk/source/ProgKyiv/DevOps/jenkins-ubuntu.pem
  - name: ng-2
    instanceType: m5.xlarge
    desiredCapacity: 2
    volumeSize: 100
    ssh:
      publicKeyPath: /Users/ymaksymchuk/source/ProgKyiv/DevOps/jenkins-ubuntu.pem
