apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prog-kyiv-ua
  region: eu-north-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    volumeSize: 30
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      # publicKeyPath: /home/maxkhal/PA/Admin57_2.pem
  - name: ng-2
    instanceType: m5.large
    desiredCapacity: 1
    volumeSize: 30
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      # publicKeyPath: /home/maxkhal/PA/Admin57_2.pem
