---
- hosts: jenkins
  become: yes
  tasks:
    - name: Update repositories cache and install "foo" package
      ansible.builtin.apt:
        name: foo
        update_cache: yes

    - name: Enable Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Configure Apache to route traffic from 80 to 8080
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        line: "Listen 8080"
        state: present

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
